@startuml

actor ciudadano

ciudadano -- (Registrar entrada)

actor "ciudadano extranjero"
 "ciudadano extranjero" -- (Tomar huellas)
 "ciudadano extranjero" --|> ciudadano
 (Tomar huellas) ..> (Registrar entrada) : extend


@enduml