@startuml

actor ciudadano

ciudadano -- (Registrar entrada)

actor "ciudadano extranjero"
 "ciudadano extranjero" -- (Tomar huellas)
 ciudadano <|-- "ciudadano extranjero"
 (Registrar entrada) <.. (Tomar huellas) : extend


@enduml