@startuml

actor :new actor:

usecase Identificarse
usecase Pagar
usecase (Elegir mensajero)
usecase Confirmar
usecase Registrarse
usecase (Pagar con tarjeta)
usecase (Pagar con transferencia)

:new actor: -- Identificarse
:new actor: -- Pagar
:new actor: -- (Elegir mensajero)
:new actor: -- Confirmar

Identificarse <.. Registrarse : extend
Pagar <|-- (Pagar con tarjeta)
Pagar <|-- (Pagar con transferencia)

@enduml